site_name: Mike Ditton
copyright: Copyright &copy; 2023 Mike Ditton
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mikeditton/
    - icon: fontawesome/brands/mastodon 
      link: https://ioc.exchange/@mikestootzz
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mike_shootzz/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/dockermike1809
    - icon: fontawesome/brands/github
      link: https://github.com/mikeshootzz
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/mike_shootzz
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCLq2y5d5J1ZRmrt4lIGnatw
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
theme:
  logo: images/developer-board.svg
  favicon: images/developer-board.svg
  language: de
  features:
    - navigation.tabs
    - toc.follow
    - content.code.copy
  name: material
  palette: 
    - primary: deep purple
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
